- id: fish_indent
  name: fish_indent
  language: system
  minimum_pre_commit_version: 2.4.0
  entry: fish_indent
  args: [-w]
  types: [fish]
- id: luaformatter
  name: luaformatter
  language: system
  entry: lua-format
  args: [-i]
  types: [lua]
- id: stylua
  name: StyLua
  language: system
  entry: stylua
  types: [lua]
- id: taplo-format
  name: Taplo format
  language: system
  entry: taplo
  args: [format]
  types: [toml]
  pass_filenames: false
